spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/yupi
    username: root
    password: 87906413
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
mybatis-plus:
  configuration:
#    用于配置MP驼峰是否转换下划线的配置
    map-underscore-to-camel-case: false